name = "forward-widget-hub"
main = ".open-next/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "forward-widget-hub-db"
database_id = "77aab095-62ac-4b42-998d-4a963377044f"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "forward-widget-hub-storage"

[vars]
BACKEND = "cloudflare"
